### ISSUE TITLE
Incorrect numbers under "Guild List View"

### ISSUE THREAD

**Issue by jonathan-nielsen** [ClassicGuildBank/ClassicGuildBank#5]
Hi, I just realized there's a minor bug with the calculation under a specific item in "Guild List View".
When i look at an item which has 98 items spread across 2 characters where one has 18 and another one has 80 it displays the correct amount. But when i expand that section i can only see 8 for one character and 10 for another. It seems it doesn't add all of the items but just simple print out one stack of items.

**Comment by athielking** [comment]
fixed in PR #14
