### ISSUE TITLE
Wrong item order when importing

### ISSUE THREAD

**Issue by Moerup** [ClassicGuildBank/ClassicGuildBank#6]
When our guild bank is neatly sorted to perfection, the webpage doesn't display it the same way..

Big OCD trigger 😄 

Attached picture of the order it imports the bag into the website.
Think it should be 1-2-3-4 from left to right.

![BankBagOrder](https://user-images.githubusercontent.com/21573343/74775110-4df92600-5295-11ea-9a53-1801fbd81303.png)
![WebsiteOrder](https://user-images.githubusercontent.com/21573343/74775112-4e91bc80-5295-11ea-8a22-750ba05be133.png)

**Comment by athielking** [comment]
Fixed in pr #12
